#!/usr/bin/python3
#x3.in.filter=^(?P<prefix>[a-z0-9._-]+\.df_complex)\.(free|reserved|used)$
#x3.out.filter=^(?P<prefix>[a-z0-9._-]+\.df_complex)\.(free|reserved|used)\.percentage$

#   ExtreMon Project
#   Copyright (C) 2009-2012 Frank Marien
#   frank@apsu.be
#
#   This file is part of ExtreMon.
#
#   ExtreMon is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   ExtreMon is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with ExtreMon.  If not, see <http://www.gnu.org/licenses/>.
#
from x3plugin import X3IO

class DF(X3IO):
  def __init__(self):
    self.log("running")
    X3IO.__init__(self,cache=True,capture=True)
    self.receive_forever()

  def receive(self,shuttle):
    for (label,value,captures) in shuttle:
      try:
        prefix=captures['prefix']
        free=float(self.cached['%s.free' % (prefix)])
        reserved=float(self.cached['%s.reserved' % (prefix)])
        used=float(self.cached['%s.used' % (prefix)])
        total=free+reserved+used
        self.put('%s.free.percentage' % (prefix),((free/total)*100.0))
        self.put('%s.reserved.percentage' % (prefix),((reserved/total)*100.0))
        self.put('%s.used.percentage' % (prefix),((used/total)*100.0))
      except KeyError:
        pass
DF()
