#!/usr/bin/python3
#x3.in.filter=^([a-z0-9._-]+\.ps_cputime)\.(user|syst)$
#x3.out.filter=^([a-z0-9._-]+\.ps_cputime)\.(user|syst)\.(avg)$
from x3plugin import X3IO
#------------------------------------------------------------------------

class PSCPU(X3IO):
  def __init__(self):
    self.log("running")
    self.cmas={}
    X3IO.__init__(self)

  def receive(self,shuttle):
    for (label,value) in shuttle:
      value=float(value)/10000.0
      try:
        cma=self.cmas[label]
        cma['value']+=(value-cma['value'])/(cma['count']+1)
        cma['count']+=1
        self.put('%s.avg' % (label),'%.2f' % (self.cmas[label]['value']))
      except KeyError:
        self.cmas[label]={'value':0.0,'count':1}

PSCPU()
